## The dataset is compiled from the 1994 Census database and contains income data.
### Data Information:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Perform data analysis using Pandas by completing the given tasks.
####

In [3]:
import pandas as pd

In [4]:
# loading the dataset
data = pd.read_csv("/data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Calculate how many men and women (attribute *sex*) are represented in this dataset.**

In [5]:
# your code
data["sex"].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. What is the average age of men (attribute *age*) across the entire dataset?**

In [6]:
# your code
print(round(data.loc[data["sex"] == "Male", "age"].mean(), 2))

39.43

**3. What is the proportion of United States citizens (*native-country* attribute)?**

In [7]:
# your code
print(round((data["native-country"] == "United-States").mean() * 100, 2))

89.59

**4-5. Calculate the mean and standard deviation of the age of those who earn more than 50K per year (the *salary* attribute) and those who earn less than 50K per year**

In [8]:
# your code
data.groupby("salary")["age"].agg(["mean", "std"])

             mean        std
salary
<=50K   36.783738  14.020088
>50K    44.249841  10.519028

**6. Is it true that people who earn more than 50k have at least a higher education? (*education indicator – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate*)**

In [9]:
# your code
higher_education = ["Bachelors", "Prof-school", "Assoc-acdm",
                    "Assoc-voc", "Masters", "Doctorate"]
high_salary=data[data["salary"] == ">50K"]
final_result=high_salary["education"].isin(higher_education).all()
print(final_result)

False

**7. Find age statistics for each race (*race* attribute) and each gender. Use *groupby* and *describe*. Find the maximum age of males of the *Asian-Pac-Islander* race.**

In [10]:
# your code
stat=data.groupby(["race","sex"])["age"].describe()
print(round(stat,2))

max_age=stat.loc[("Asian-Pac-Islander","Male"),"max"]
print(max_age)

                             count   mean    std   min   25%   50%    75%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.12  13.11  17.0  27.0  36.0  46.00
                   Male      192.0  37.21  12.05  17.0  28.0  35.0  45.00
Asian-Pac-Islander Female    346.0  35.09  12.30  17.0  25.0  33.0  43.75
                   Male      693.0  39.07  12.88  18.0  29.0  37.0  46.00
Black              Female   1555.0  37.85  12.64  17.0  28.0  37.0  46.00
                   Male     1569.0  37.68  12.88  17.0  27.0  36.0  46.00
Other              Female    109.0  31.68  11.63  17.0  23.0  29.0  39.00
                   Male      162.0  34.65  11.36  17.0  26.0  32.0  42.00
White              Female   8642.0  36.81  14.33  17.0  25.0  35.0  46.00
                   Male    19174.0  39.65  13.44  17.0  29.0  38.0  49.00

                            max
race               sex
Amer-Indian-Eskimo Female  80.0
                   Male    82.0
Asian-Pac-Islander Female  75.0
                   Male    90.0
Black              Female  90.0
                   Male    90.0
Other              Female  74.0
                   Male    77.0
White              Female  90.0
                   Male    90.0
90.0

**8. Among whom is the proportion of high-earning individuals (>50K) higher: married or single men (*marital-status* indicator)? We consider those whose *marital-status* begins with *Married* (Married-civ-spouse, Married-spouse-absent, or Married-AF-spouse) to be married; the rest are considered single.**

In [11]:
# your code
men = data[data["sex"]=="Male"].copy()
men["is_married"] = men["marital-status"].str.startswith("Married")
men["high_salary"] = men["salary"] == ">50K"
result = men.groupby("is_married")["high_salary"].mean()
print(round(result*100),2)

is_married
False     8.0
True     44.0
Name: high_salary, dtype: float64 2

**9. What is the maximum number of hours a person works per week (hours-per-week indicator)? How many people work that many hours, and what percentage of them earn a lot?**

In [12]:
# your code
max_hours=data["hours-per-week"].max()

max_hours_people=data[data["hours-per-week"]==max_hours]

count_people=len(max_hours_people)

print("Max Hours: ",max_hours)
print("People Count: ",count_people)
print("Rich percent: ",round((max_hours_people["salary"]==">50K").mean()*100,2))

Max Hours:  99
People Count:  85
Rich percent:  29.41

**10. Calculate the average working hours (*hours-per-week*) of low and high earners (*salary*) for each country (*native-country*).**

In [13]:
# your code
avg_work_hours=data.groupby(["native-country","salary"])["hours-per-week"].mean()
print(round(avg_work_hours,2))

native-country  salary
?               <=50K     40.16
                >50K      45.55
Cambodia        <=50K     41.42
                >50K      40.00
Canada          <=50K     37.91
                          ...
United-States   >50K      45.51
Vietnam         <=50K     37.19
                >50K      39.20
Yugoslavia      <=50K     41.60
                >50K      49.50
Name: hours-per-week, Length: 82, dtype: float64

**11.Group people into age groups *young*, *adult*, *retiree*, where:**
* *young* corresponds to 16-35 years old
* *adult* - 35-70 years old
* *retiree* - 70-100 years old

**Enter the name of the appropriate age group for each person in the new AgeGroup column.**

In [14]:
# your code
data["AgeGroup"]=None

data.loc[(data["age"] >= 16) & (data["age"] <= 35), "AgeGroup"] = "young"
data.loc[(data["age"] > 35) & (data["age"] <= 70), "AgeGroup"] = "adult"
data.loc[(data["age"] > 70) & (data["age"] <= 100), "AgeGroup"] = "retiree"

print(data[["age", "AgeGroup"]].head())

   age AgeGroup
0   39    adult
1   50    adult
2   38    adult
3   53    adult
4   28    young

**12-13. Determine the number of people earning >50K in each age group (AgeGroup column), and also output the name of the age group in which people most often earn more than 50K (>50K)**

In [15]:
# your code
data["salary"] = data["salary"].str.strip()
rich_people=data[data["salary"] == ">50K"]
result=rich_people["AgeGroup"].value_counts()

print(result)

most_common_group=result.idxmax()
print("Age group with most >50K earners:", most_common_group)

AgeGroup
adult      6042
young      1705
retiree      94
Name: count, dtype: int64
Age group with most >50K earners: adult

**14. Group people by employment type (the occupation column) and determine the number of people in each group. Then write a filter function, filter_func, that will return only those groups in which the average age (the age column) is 40 or less and in which all employees work more than 5 hours per week (the hours-per-week column).**

In [16]:
# your code
occupation_counts = data.groupby("occupation").size()
print(occupation_counts)

def filter_func(group):
  average_age = group["age"].mean()
  all_work_more_than_5 = (group["hours-per-week"] > 5).all()

  return average_age <= 40 and all_work_more_than_5

filtered_data=data.groupby("occupation").filter(filter_func)
print(filtered_data)

occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64
       age    workclass  fnlwgt     education  education-num  \
442     24  Federal-gov  191073       HS-grad              9
1300    29  Federal-gov  301010  Some-college             10
14613   39  Federal-gov  227597       HS-grad              9
16111   24  Federal-gov  287988     Bachelors             13
18034   34  Federal-gov  172716          12th              8
18644   23  Federal-gov  163870  Some-college             10
18769   30  Federal-gov   76313       HS-grad              9
25799   46  Federal-gov  344415       Masters             14
32316   23  Federal-gov  173851       HS-grad              9

           marital-status    occupation    relationship                race  \
442         Never-married  Armed-Forces       Own-child               White
1300        Never-married  Armed-Forces   Not-in-family               Black
14613       Never-married  Armed-Forces   Not-in-family               White
16111       Never-married  Armed-Forces   Not-in-family               White
18034  Married-civ-spouse  Armed-Forces         Husband               White
18644       Never-married  Armed-Forces  Other-relative               White
18769  Married-civ-spouse  Armed-Forces  Other-relative  Amer-Indian-Eskimo
25799  Married-civ-spouse  Armed-Forces         Husband               White
32316       Never-married  Armed-Forces   Not-in-family               White

        sex  capital-gain  capital-loss  hours-per-week native-country salary  \
442    Male             0             0              40  United-States  <=50K
1300   Male             0             0              60  United-States  <=50K
14613  Male             0             0              50  United-States  <=50K
16111  Male             0             0              40  United-States  <=50K
18034  Male             0             0              40  United-States  <=50K
18644  Male             0             0              40  United-States  <=50K
18769  Male             0             0              48  United-States  <=50K
25799  Male             0          1887              40  United-States   >50K
32316  Male             0             0               8  United-States  <=50K

      AgeGroup
442      young
1300     young
14613    adult
16111    young
18034    young
18644    young
18769    young
25799    adult
32316    young